spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_services
    username: rs
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8181


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
    expiration-time: 3600000

